### ISSUE TITLE
Be explicit about conversions

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/countryyear#3]
Avoid using packages like countrycode to identify bad names or codes. Use that first for diagnostic, but then hard-code changes in the scrapers. Countrycode might change, and it's more transparent to users what we do this way.

**Comment by cjyetman** [comment]
There must be some baseline reference to compare to... a list of entities (countries) and some unique way of identifying them. Could be the country name, ensured to be unique, or could be a unique key. Either way, when the scrapers get data from a source, they will need to match each country to something in the baseline reference to facilitate merging with other sources.

I was using `countrycode`, and hence the underlying `countrycode_data`, as that baseline. I agree that's not ideal, but in lieu of anything else, it's a good start. Maybe you/we should consider creating a master reference CSV with one line for each unique country, a column for a unique key, and a column for an unambiguous description of the country it refers to (e.g. 'Ethiopia (1975-1991)'). COW is obviously a good start for that.

**Comment by vincentarelbundock** [comment]
CoW doesn't have all the ISO codes for example, so it would need to be CoWPlus...

Right now, regexes act as de factor unique identifiers. Not sure how that plays out in the panel context.

I'm working on countryyear right now. So far, here are a few of the things I'm trying to do:

Have one script per source, which downloads and cleans the data. Then it save a "clean" version in a source directory (no longer sure we need to keep the raw files). Those don't have a unique ID yet. This should all be handled in a separate merge script. 

I was thinking about using regexes to do the merging, since all codes are accompanied by english names anyway.

**Comment by vincentarelbundock** [comment]
Simple example of how I would present things, using your original eurostat scraping script:

https://github.com/vincentarelbundock/countryyear/blob/master/utilities/eurostat.R

**Comment by vincentarelbundock** [comment]
That doesn't take care of merging, so we don't need a unique ID at that stage yet.

**Comment by cjyetman** [comment]
yeah, even CoW is not 'complete'. Building such a 'complete' list will be an undertaking on its own. It may even be necessary to have separate unique IDs for the same country before and after one of the destination codes changed the code for said country.

In regards to the scrapers and the 'clean' versions... if not worried about merging yet, why do any editing/changing of the country names as you did in [eurostat.R](https://github.com/vincentarelbundock/countryyear/blob/master/utilities/eurostat.R)? Shouldn't the strategy be to simply distill everything down to a simple CSV with one 'code' column and one 'match' column... 'code' being the source's coding scheme and 'match' being whatever information the source provides that will help the merger connect it to the appropriate entity in the baseline reference?

**Comment by cjyetman** [comment]
In other words... to what do we convert the names, in Eurostat for example? e.g. when changing 'Puerto Rico (US)' to 'Puerto Rico', where does 'Puerto Rico' come from?

**Comment by vincentarelbundock** [comment]
You're right.

I think transparency requires that these choices be made in a centralized location.

We can probably drop units that will never be included though (e.g., "Franc Zone").

**Comment by vincentarelbundock** [comment]
BTW, what's the difference between stuff in the importers folder and seemingly equivalent file in the utilities folder?

I think we should just have a folder with scripts that are just named after the source.

**Comment by cjyetman** [comment]
agreed. I think a lot of the work can be done before that 'centralized location' is created/determined... I wouldn't suggest halting everything until that is done. Modifying the scrapers later on to conform to whatever standard arises will not be too difficult.

**Comment by cjyetman** [comment]
The scripts in [utilities/countrycode_importers](https://github.com/vincentarelbundock/countryyear/tree/master/utilities/countrycode_importers) are specific to `countrycode` versus `countryyear`. You asked me to put them here instead of there, but to distinguish them, I put them in a sub-directory. There are significant differences. For instance, `countrycode` has no concept of year, so those scripts pick the most recent year/version of a country and exclude the rest. Obviously, you won't want that here in `countryyear`. So, they may be a useful reference, and I used them directly to import data on `countrycode`, but they would need to be modified to work with `countryyear`.

**Comment by vincentarelbundock** [comment]
OK, great.

So I'll leave them there, but eventually the goal of this repo is to make those scripts obsolete, since the countrycode dictionary will be derived entirely from countryyear.

**Comment by cjyetman** [comment]
understood

**Comment by vincentarelbundock** [comment]
I made a fair bit of progress today but have to move on to other things now.

Would be curious about what @cjyetman thinks of this file: https://github.com/vincentarelbundock/countryyear/blob/master/utilities/merge.R

The idea is to have:

1. One script per data source in the utilities folder which scrapes the data and saves a reasonably clean CSV file to data/source.
2. For cross-sectional data, we use regexes as unique identifier in merge.R
3. In merge.R, we explicitly filter out country names which match multiple regexes.
4. Merge the cross-sectional file based on the common key "regex"

**Comment by vincentarelbundock** [comment]
And now I am wobbling on the core design principle of centralization. Should we just put the clean-up stuff in each of the sources' respective scripts?

**Comment by cjyetman** [comment]
some thoughts after reviewing [utilities/merge.R](https://github.com/vincentarelbundock/countryyear/blob/master/utilities/merge.R)...

- would advise using more explicit options for read.csv (see #5)
- my ultra-cautiousness with 'raw'/'source' data leads me to prefer modifying a copy of the country name column rather than the original column itself, and then converting to regex from the copy but leaving the original intact (for example here [utilities/merge.R #L15-L16])(https://github.com/vincentarelbundock/countryyear/blob/master/utilities/merge.R#L15-L16)
- I wonder why in some places you convert a country name to a different name (presumably because it will match better with `countrycode`?) using the `ReplaceDict()` function (e.g. [utilities/merge.R #L10-L15](https://github.com/vincentarelbundock/countryyear/blob/master/utilities/merge.R#L10-L15)), but in other cases filter out a country name (e.g. [utilities/merge.R #L22-L25](https://github.com/vincentarelbundock/countryyear/blob/master/utilities/merge.R#L22-L25)). How do you decide which strategy to use?
- what is the purpose of [this](https://github.com/vincentarelbundock/countryyear/blob/master/utilities/merge.R#L121) converting a data frame to a data frame?
- you can alphabetize the data frame columns in the dplyr chain with `select(order(colnames(.)))`
- `write.csv` has similar problems to `read.csv`
- in the result, `country.name.XX` columns are the official UN names, which means many rows have `<NA>`s. My inclination is that those columns should be named `country.name.un.XX` and there should be `country.name.XX` columns that are complete so that this thing can at least spit out some human readable, unique name for each row
- I also wonder if it makes more sense to have the code/source specific changes in the source specific prep scripts, so that **everything** related to a specific source is in one file... not super opinionated about it at the moment, but definitely recognize the possible benefit of that
- minor stylistic choice, in the past when creating a bunch of intermediary data frames which later on I will want to commonly apply some things to, I preferred to start out with `dflist <- list()` at the top, and then at the end of each importing section add `dflist <- c(dflist, wb = list(wb))`, rather than compiling them all into a list at the end... that way you explicitly do that for each importation instead of depending on having your list of data frames at the end being correct (e.g. [`crosssection = list(iso, wb, ecb, fao, ioc, unpd, wvs, un_names)`](https://github.com/vincentarelbundock/countryyear/blob/master/utilities/merge.R#L95))

**Comment by vincentarelbundock** [comment]
I agree with all you write, and will try to make the recommended changes at some point (my open source work time allocation is pretty spent now, but I may have energy at night at some point).

I converted your list to check list. One those are done, we can close this issue and discuss design issues piecemeal in their own issues. 

Quick responses:

- OK, let's try putting all cleaning related stuff in each source's own script.
- Filter vs ReplaceDict is a temporary solution guided by the relative cost of dropping Channel Islands vs. United Kingdom. Eventually we'll want better regex for all of those cases.
- Not sure about country.name.un.en. Do users really care? I'm thinking we should just have a well-documented order of preference (e.g., iso > un > cow > polity), and create one country.name.en which covers everything. Other languages will only have UN names (and maybe ISO), and NA where those don't exist.

**Comment by cjyetman** [comment]
My point about the `country.name.en` column was that, as it is (UN official name), there are rows/entities that do not have an official UN name, and therefore the following hypothetical code would return `<NA>` (assuming that it is using [data/crosssection.csv](https://github.com/vincentarelbundock/countryyear/blob/master/data/crosssection.csv) as its underlying lookup table)...
```r
countryyear(source = 'Aruba', year = 2012, orig = 'country.name', dest = 'country.name')
```
but, it sounds like you already know that (e.g. "create one country.name.en which covers everything").

**Comment by vincentarelbundock** [comment]
The new approach is to have a composite English name mostly based on CLDR, with a defined order of priority: CLDR > ISO > UN > CoW > Polity > Manual.

The other names will all be available in the dictionary as well.
