### ISSUE TITLE
ISO codes importer

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/countryyear#4]
@cjyetman 

Your ISO code importer looks awesome, but I wasn't able to run it locally. For some reason RSelenium (which I have never used before) can't find my local phantomjs installation (and prints a warning that phantom support will be remove anyway).

Should I just go back to the CSV file I copy/pasted manually from the ISO website?

**Comment by cjyetman** [comment]
Phantomjs needs to be installed separately, and honestly it can be a real pain and it's a different process depending on your platform. Unfortunately the ISO source website generates its interface with JavaScript, which leaves limited options for scraping. It has to be rendered and run through a JVM to get to everything. The script could be modified so that RSelenium remote controls a browser like Firefox or Chrome, which is possibly easier to install on whatever platform you are using, but then it won't be 'headless' anymore. I'll keep thinking of alternatives, but that was the best I could come up with at the moment. Technically, there's also a way to use `httr` to download the file directly, but you have to hack the headers and get the server to create a cookie for you first. I had something like that working, but it seemed way to complicated and I feared it might break in the near term.

**Comment by cjyetman** [comment]
FYI... phantomjs is not an R package, so you have to install it through whatever your platform's process is for that kind of thing. I thought that RSelenium had recently made efforts to make the installation/locating of phantomjs easier, but it's been a long time since I messed with the setup.

**Comment by vincentarelbundock** [comment]
Yeah, well I have it installed (on this linux machine) and can launch phantomjs from the terminal, but R won't link up, even if I give it the path.

Perhaps for now it would just be easier for me to cut and paste this in a spreadsheet.

**Comment by cjyetman** [comment]
Supposedly you can set the phantomjs path explicitly. See here: ftp://cran.r-project.org/pub/R/web/packages/RSelenium/vignettes/RSelenium-headless.html

**Comment by cjyetman** [comment]
Oh sorry, now see that you have tried setting the path. One other thing that I vaguely remember is that it's sensitive to the version of phantomjs. So, maybe make sure the version you have installed is compatible?

**Comment by vincentarelbundock** [comment]
I copied things by had to a CSV file, which is what we use now. We can think about a different approach later, but this works for now.

https://github.com/vincentarelbundock/countryyear/commit/1305d7ab473a07c92d732a06d057a2192d118c2d

**Comment by cjyetman** [comment]
I looked into alternatives... it does not seem possible. They use a csrf token, which is unique per session or request, and generated by a JavaScript script. I can't think of any way to get around that without running the JavaScript through a JVM, which is the primary advantage/reason for using phantomjs in this case.

**Comment by vincentarelbundock** [comment]
Hank's for looking into this.

I'm not sure this is such a big deal. One problem I've been worrying about is that this change in procedure really increases the cost of introducing new codes for contributors (or me).

I suppose it's OK to have cut and pasted data (at least as temporary measure).

**Comment by cjyetman** [comment]
I just made some changes to the ISO importer in [commit 30c8e4f](https://github.com/vincentarelbundock/countryyear/commit/30c8e4f9ff1f1ecbcd522b8c42977623560da9de) because `RSelenium::phantom()` has been deprecated in favor of `RSelenium::rsDriver()` which is supposedly better because it leverages the `wdman` package. Also, there were very recent (< 2 weeks) relevant changes/fixes to RSelenium and wdman.

wdman manages the binaries for phantomjs, etc., so that may solve your problem with it not finding your phantomjs

iso importer is here: [utilities/countrycode_importers_obsolete/iso_importer.R](https://github.com/vincentarelbundock/countryyear/blob/master/utilities/countrycode_importers_obsolete/iso_importer.R)

You might want to give it a go again. Here are a few things to check:

- make sure you have the most recent version of RSelenium installed ([currently 1.7.1](https://github.com/ropensci/RSelenium/releases))
- make sure you have the most recent version of wdman installed ([currently 0.2.2](https://github.com/johndharrison/wdman/releases))
- make sure your system is running a recent JVM version (1.8.xxx); on a command line `java -version`

**Comment by vincentarelbundock** [comment]
I can't get this to work, but this is almost certainly a problem on my end (compiler issues means I'm running everything through Docker, so there might be some communication issues there).

Can you overwrite the iso.R importer in the main utilities folder, and save the output in the data/source folder? 

For now, I'll just comment out he selenium script in the merge.R and load directly from whatever CSV the script produces on your machine.

**Comment by cjyetman** [comment]
done in [commit e7b31ef](https://github.com/vincentarelbundock/countryyear/commit/e7b31effd82d107ac3e1844991eeb8d37e960899)
